version: "3.8"

services:
  db:
    image: postgres:14
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Use named volume to persist data

  app:
    build: .
    container_name: auth_api
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
      HOST: ${HOST}
      PORT: ${PORT}
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      ACCCESS_TOKEN_AGE: ${ACCCESS_TOKEN_AGE}
    restart: always
    command: sh -c "sleep 10 && npm run migrate:up && npm start"

volumes:
  pgdata: # Define the named volume here
