version: "3.8"

services:
  product_api:
    build: .
    container_name: product_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
